# Form implementation generated from reading ui file 'Application/pyui/mainscreen.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 164)
        self.workswithvideobutton = QtWidgets.QPushButton(Form)
        self.workswithvideobutton.setGeometry(QtCore.QRect(20, 20, 601, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.workswithvideobutton.setFont(font)
        self.workswithvideobutton.setObjectName("workswithvideobutton")
        self.recordvideowithprocess = QtWidgets.QPushButton(Form)
        self.recordvideowithprocess.setGeometry(QtCore.QRect(20, 90, 601, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.recordvideowithprocess.setFont(font)
        self.recordvideowithprocess.setObjectName("recordvideowithprocess")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.workswithvideobutton.setText(_translate("Form", "Работа с записанным видео"))
        self.recordvideowithprocess.setText(_translate("Form", "Запись видео с последующей обработкой"))
